    Tracker:AddLocations("locations/overworld.json")
    Tracker:AddLocations("locations/underworld.json")
    Tracker:AddLocations("locations/moon.json")
    Tracker:AddLocations("locations/overworld_hints.json")
    Tracker:AddLocations("locations/underworld_hints.json")
    Tracker:AddLocations("locations/moon_hints.json")
